version: "3"

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mern-todo
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      MONGO_URI: mongodb://mongo:27017/mern-todo
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/devops_cuoikhoa:/home/ubuntu/devops_cuoikhoa

volumes:
  mongo_data:
  jenkins_home: