name: MERN CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      # Frontend
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build React App
        working-directory: frontend
        run: npm run build